// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2FOli7ZWZo8rNevtbjT4oGvG49nwV-Fs',
    appId: '1:995414676211:web:c56d29d50051a849f55d86',
    messagingSenderId: '995414676211',
    projectId: 'finance-b6b33',
    authDomain: 'finance-b6b33.firebaseapp.com',
    storageBucket: 'finance-b6b33.firebasestorage.app',
    measurementId: 'G-NB4NYCY916',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDat_a4QKPWgNXKwyecStvZ_xlsuoSF0Y',
    appId: '1:995414676211:android:62dcc32d5635052cf55d86',
    messagingSenderId: '995414676211',
    projectId: 'finance-b6b33',
    storageBucket: 'finance-b6b33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtgZ1udIWDPfqGh9ZkGR6JgDzFvKtGW68',
    appId: '1:995414676211:ios:64594b0bc0719f93f55d86',
    messagingSenderId: '995414676211',
    projectId: 'finance-b6b33',
    storageBucket: 'finance-b6b33.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtgZ1udIWDPfqGh9ZkGR6JgDzFvKtGW68',
    appId: '1:995414676211:ios:64594b0bc0719f93f55d86',
    messagingSenderId: '995414676211',
    projectId: 'finance-b6b33',
    storageBucket: 'finance-b6b33.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2FOli7ZWZo8rNevtbjT4oGvG49nwV-Fs',
    appId: '1:995414676211:web:ce00aeefb9651cfcf55d86',
    messagingSenderId: '995414676211',
    projectId: 'finance-b6b33',
    authDomain: 'finance-b6b33.firebaseapp.com',
    storageBucket: 'finance-b6b33.firebasestorage.app',
    measurementId: 'G-NNMDTVC350',
  );
}
